server:
  port: 8081

logging:
  level:
    com:
      netflix:
        hystrix: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
  redis:
    database: local
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    connectTimeout: 10000
#    clientName: