server:
  port: 8081

logging:
  level:
    com:
      netflix:
        hystrix: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
spring:
  application:
    name: rpc